name: foodexpress
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+6

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^0.1.2
  flutter_staggered_animations: "^0.1.2"
  liquid_pull_to_refresh: ^2.0.0
  motion_tab_bar: ^0.0.1
  simple_animations: ^1.3.3
  page_transition: ^1.1.7+2
  flutter_svg: ^0.17.4
  google_fonts: ^0.3.5
  smooth_star_rating: 1.0.2
  http: ^0.12.0
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.6
  provider: ^4.0.2
  flutter_range_slider: "^1.0.1"
  image_picker: 0.6.5+3
  geolocator: ^5.3.1
  flutter_credit_card: ^0.1.3
  stripe_payment: ^1.0.7
  progress_dialog: ^1.2.2
  contactus: ^1.1.5
  firebase_messaging: ^7.0.3
  firebase_analytics: ^6.3.0
  device_info: 1.0.0
  razorpay_flutter: ^1.2.2
  flutter_paystack: ^1.0.3+1
  toast: ^0.1.5
  carousel_pro: ^1.0.0
  numeric_keyboard: ^1.0.0
  carousel_slider: ^2.2.1
  getwidget: ^1.1.0
  google_sign_in: 4.5.3
  cached_network_image: ^2.3.1
  liquid_swipe: ^1.5.0
  firebase_auth: ^0.18.0
  firebase_database: ^4.4.0
  mvc_pattern: ^6.3.0
  shimmer: ^1.1.1
  webview_flutter: ^1.0.7
  paytm: ^2.0.0
  progress_hud: ^1.1.0
  rounded_loading_button: ^1.0.0
  flutter_slidable: ^0.5.7
  loading: ^1.0.2
  timer_builder: ^1.3.0
  lipsum: 1.0.1
  nb_utils: 3.1.6+7
  progressive_image: ^1.0.1
  firebase_core: ^0.5.3
  flutter_webview_plugin: ^0.3.11
  new_version: ^0.0.5




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  

flutter_icons:
#  image_path_android: "assets/images/icon.png"
  android: true
  ios: true
  image_path: 'assets/images/icon.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/steak.png
    - assets/login.png
    - assets/images/icon.png
    - assets/icons/ic_thank_you.png
    - assets/images/ic_logout.png
    - assets/icons/dropdown.svg
    - assets/icons/maps-and-flags.svg
    - assets/icons/maps-and-flags.svg
    - assets/images/cash_delivery.jpg
    - assets/images/pay_pickup.png
    - assets/images/paypal.png
    - assets/images/stripe.png
    - assets/images/razorpay.png
    - assets/images/paystack.png
    - assets/success_logo.png
    - assets/unsuccess_logo.png
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/4.jpg
    - assets/images/c1.png
    - assets/images/c2.png
    - assets/images/c3.jpg
    - assets/images/3line.png
    - assets/images/map.jpg
    - assets/images/header_background.png
    - assets/images/food_ic_walk1.svg
    - assets/images/food_ic_walk2.svg
    - assets/images/food_ic_walk3.svg
    - assets/images/paytm.jpg
    - assets/images/paymentlogo.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico.ttf
    - family: Fryo
      fonts:
        - asset: fonts/Fryo.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
